import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { FileText, FileJson, Globe, File } from "lucide-react";
import { motion } from "framer-motion";
import { toast } from "sonner";
import { useScanContext } from "@/context/ScanContext";

function generateJsonReport(vulnerabilities: any[], report: any) {
  return JSON.stringify({
    reportId: report.id,
    title: report.title,
    type: report.type,
    scanId: report.scanId,
    generatedAt: report.date,
    totalFindings: report.findings,
    vulnerabilities: vulnerabilities.map(v => ({
      id: v.id, title: v.title, severity: v.severity, riskScore: v.riskScore,
      category: v.category, owaspCategory: v.owaspCategory, status: v.status,
      description: v.description, evidence: v.evidence, recommendation: v.recommendation,
      affectedUrl: v.affectedUrl, detectedAt: v.detectedAt,
    })),
  }, null, 2);
}

function generateHtmlReport(vulnerabilities: any[], report: any) {
  const vulnRows = vulnerabilities.map(v => `
    <tr>
      <td style="padding:8px;border:1px solid #333">${v.id}</td>
      <td style="padding:8px;border:1px solid #333">${v.title}</td>
      <td style="padding:8px;border:1px solid #333;color:${v.severity === 'Critical' ? '#ef4444' : v.severity === 'High' ? '#f59e0b' : '#3b82f6'}">${v.severity}</td>
      <td style="padding:8px;border:1px solid #333">${v.riskScore}</td>
      <td style="padding:8px;border:1px solid #333">${v.owaspCategory}</td>
      <td style="padding:8px;border:1px solid #333">${v.status}</td>
    </tr>`).join("");

  const vulnDetails = vulnerabilities.map(v => `
    <div style="border:1px solid #333;border-radius:8px;padding:16px;margin-bottom:16px;background:#1a1a2e">
      <h3 style="color:#00ff88">${v.id}: ${v.title}</h3>
      <p><strong>Severity:</strong> ${v.severity} | <strong>Risk Score:</strong> ${v.riskScore} | <strong>Status:</strong> ${v.status}</p>
      <p><strong>Category:</strong> ${v.owaspCategory}</p>
      <p><strong>Affected URL:</strong> ${v.affectedUrl}</p>
      <h4>Description</h4><p>${v.description}</p>
      <h4>Evidence</h4><p style="background:#0d0d1a;padding:8px;border-radius:4px;font-family:monospace">${v.evidence}</p>
      <h4>Recommendation</h4><p>${v.recommendation}</p>
    </div>`).join("");

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>${report.title}</title>
<style>
@import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;700&display=swap');
body{font-family:'JetBrains Mono',monospace;background:#0f0f23;color:#e0e0e0;max-width:900px;margin:0 auto;padding:40px}
h1,h2,h3,h4{font-family:'JetBrains Mono',monospace}
h1{color:#00ff88}h2{color:#00d4ff;border-bottom:1px solid #333;padding-bottom:8px}
table{width:100%;border-collapse:collapse;margin:16px 0}th{background:#1a1a2e;padding:8px;border:1px solid #333;text-align:left}
.header{text-align:center;border-bottom:2px solid #00ff88;padding-bottom:20px;margin-bottom:30px}
.meta{display:flex;justify-content:space-between;background:#1a1a2e;padding:12px;border-radius:8px;margin:16px 0}</style></head>
<body>
<div class="header"><h1>CYBERION</h1><p>Security Assessment Report</p></div>
<h1>${report.title}</h1>
<div class="meta"><span>Report ID: ${report.id}</span><span>Scan: ${report.scanId}</span><span>Date: ${report.date}</span><span>Findings: ${report.findings}</span></div>
<h2>Summary</h2>
<table><thead><tr><th>ID</th><th>Title</th><th>Severity</th><th>Risk</th><th>OWASP</th><th>Status</th></tr></thead><tbody>${vulnRows}</tbody></table>
<h2>Detailed Findings</h2>${vulnDetails}
<hr><p style="text-align:center;color:#666;margin-top:40px">Generated by CYBERION — For authorized security testing only</p>
</body></html>`;
}

function generateTextReport(vulnerabilities: any[], report: any) {
  const lines = [
    "═".repeat(60),
    "CYBERION — Security Assessment Report",
    "═".repeat(60),
    "",
    `Report ID:  ${report.id}`,
    `Title:      ${report.title}`,
    `Type:       ${report.type}`,
    `Scan ID:    ${report.scanId}`,
    `Date:       ${report.date}`,
    `Findings:   ${report.findings}`,
    "",
    "─".repeat(60),
    "VULNERABILITY SUMMARY",
    "─".repeat(60),
    "",
  ];

  vulnerabilities.forEach(v => {
    lines.push(`[${v.severity.toUpperCase()}] ${v.id}: ${v.title}`);
    lines.push(`  Risk Score: ${v.riskScore} | Status: ${v.status}`);
    lines.push(`  Category: ${v.owaspCategory}`);
    lines.push(`  URL: ${v.affectedUrl}`);
    lines.push("");
    lines.push(`  Description: ${v.description}`);
    lines.push(`  Evidence: ${v.evidence}`);
    lines.push(`  Recommendation: ${v.recommendation}`);
    lines.push("");
    lines.push("─".repeat(60));
    lines.push("");
  });

  lines.push("", "Generated by CYBERION — For authorized security testing only");
  return lines.join("\n");
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export default function Reports() {
  const { scans, vulnerabilities } = useScanContext();

  // Dynamically generate reports from scans
  const reports = scans
    .filter(s => s.status === "completed")
    .map((scan, i) => ({
      id: `RPT-${String(i + 1).padStart(3, "0")}`,
      title: `Full Security Assessment - ${scan.id}`,
      type: i % 2 === 0 ? "Technical" : "Executive",
      scanId: scan.id,
      targetUrl: scan.targetUrl,
      date: scan.completedAt ? new Date(scan.completedAt).toISOString().split("T")[0] : new Date(scan.startedAt).toISOString().split("T")[0],
      findings: Object.values(scan.vulnCount).reduce((a, b) => a + b, 0),
      pages: Math.max(8, Object.values(scan.vulnCount).reduce((a, b) => a + b, 0) * 4),
    }));

  const handleDownload = (report: typeof reports[0], format: string) => {
    // Filter vulnerabilities relevant to this scan's target URL
    const relevantVulns = vulnerabilities.filter(v => v.affectedUrl.includes(report.targetUrl) || report.targetUrl.includes("juice-shop"));

    const vulnsToUse = relevantVulns.length > 0 ? relevantVulns : vulnerabilities;

    switch (format) {
      case "json": {
        const json = generateJsonReport(vulnsToUse, report);
        downloadFile(json, `${report.id}_report.json`, "application/json");
        break;
      }
      case "html": {
        const html = generateHtmlReport(vulnsToUse, report);
        downloadFile(html, `${report.id}_report.html`, "text/html");
        break;
      }
      case "pdf": {
        const text = generateTextReport(vulnsToUse, report);
        downloadFile(text, `${report.id}_report.txt`, "text/plain");
        break;
      }
    }
    toast.success(`${format.toUpperCase()} report downloaded`);
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold font-mono tracking-tight">Reports</h1>
        <p className="text-sm text-muted-foreground mt-1">Generated security assessment reports</p>
      </div>

      <div className="space-y-4">
        {reports.map((report, i) => (
          <motion.div
            key={report.id}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.1 }}
          >
            <Card className="p-5 bg-card border-border">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <div className="flex items-start gap-3">
                  <div className="rounded-md bg-primary/10 p-2">
                    <FileText className="h-5 w-5 text-primary" />
                  </div>
                  <div>
                    <p className="font-medium text-sm">{report.title}</p>
                    <p className="text-xs text-muted-foreground font-mono">{report.targetUrl}</p>
                    <div className="flex gap-2 mt-1.5">
                      <Badge variant="outline" className="text-xs">{report.type}</Badge>
                      <span className="text-xs text-muted-foreground font-mono">{report.findings} findings • {report.pages} pages</span>
                    </div>
                    <p className="text-xs text-muted-foreground mt-1 font-mono">{report.date}</p>
                  </div>
                </div>
                <div className="flex gap-2">
                  <Button variant="outline" size="sm" onClick={() => handleDownload(report, "pdf")} className="gap-1.5 text-xs">
                    <File className="h-3 w-3" /> PDF
                  </Button>
                  <Button variant="outline" size="sm" onClick={() => handleDownload(report, "html")} className="gap-1.5 text-xs">
                    <Globe className="h-3 w-3" /> HTML
                  </Button>
                  <Button variant="outline" size="sm" onClick={() => handleDownload(report, "json")} className="gap-1.5 text-xs">
                    <FileJson className="h-3 w-3" /> JSON
                  </Button>
                </div>
              </div>
            </Card>
          </motion.div>
        ))}
        {reports.length === 0 && (
          <p className="text-sm text-muted-foreground text-center py-8">No completed scans yet. Start a scan to generate reports.</p>
        )}
      </div>
    </div>
  );
}
